language: go
script:
- make ci
- git diff --exit-code
before_install:
- openssl aes-256-cbc -K $encrypted_e3dcfd3c0dc5_key -iv $encrypted_e3dcfd3c0dc5_iv
  -in env.yaml.enc -out env.yaml -d
- openssl aes-256-cbc -K $encrypted_e3dcfd3c0dc5_key -iv $encrypted_e3dcfd3c0dc5_iv
  -in test-66d6599d8f1b.json.enc -out test-66d6599d8f1b.json -d
deploy:
  provider: gae
  keyfile: test-66d6599d8f1b.json
  project: positive-apex-202905
